# Generated by Django 6.0.3 on 2026-03-23 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_active_user_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_combustible', models.CharField(max_length=20)),
                ('luces', models.BooleanField(default=False)),
                ('frenos', models.BooleanField(default=False)),
                ('llantas', models.BooleanField(default=False)),
                ('espejos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehiculo')),
            ],
        ),
    ]
