# Generated by Django 6.0.3 on 2026-05-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_movimiento_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero_empleado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
