# Generated by Django 6.0.3 on 2026-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_2fa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_notification_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
