# Generated by Django 6.0.3 on 2026-05-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_email_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_notification_email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
