# Generated by Django 6.0.3 on 2026-03-27 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('licencia', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=30, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_entidad', models.CharField(choices=[('tracto', 'Tractocamión'), ('empleado', 'Vehículo de empleado'), ('visitante', 'Vehículo de visitante/proveedor')], max_length=20)),
                ('categoria', models.CharField(choices=[('tractocamion', 'Tractocamión'), ('camioneta', 'Camioneta'), ('automovil', 'Automóvil'), ('moto', 'Moto'), ('otro', 'Otro')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_interna', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo_entidad', models.CharField(choices=[('tracto', 'Tractocamión'), ('empleado', 'Vehículo de empleado'), ('visitante', 'Vehículo de visitante/proveedor')], max_length=20)),
                ('categoria', models.CharField(choices=[('tractocamion', 'Tractocamión'), ('camioneta', 'Camioneta'), ('automovil', 'Automóvil'), ('moto', 'Moto'), ('otro', 'Otro')], max_length=20)),
                ('propietario', models.CharField(blank=True, max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('numero_economico', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_checklist', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitanteRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visitante', models.CharField(choices=[('proveedor', 'Proveedor'), ('visitante', 'Visitante'), ('otro', 'Otro')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('vehiculo_tipo_general', models.CharField(blank=True, max_length=80)),
                ('placas', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('turno_apertura', 'Apertura de turno'), ('turno_cierre', 'Cierre de turno'), ('registro_acceso', 'Registro de acceso'), ('checklist', 'Registro de checklist'), ('admin_accion', 'Acción administrativa'), ('notificacion', 'Notificación')], max_length=30)),
                ('descripcion', models.TextField()),
                ('referencia_modelo', models.CharField(blank=True, max_length=100)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_general', models.CharField(default='pendiente', max_length=50)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_registrados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_realizados', to='platform_core.plantillachecklist')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('obligatorio', models.BooleanField(default=True)),
                ('tipo_respuesta', models.CharField(choices=[('booleano', 'Sí/No'), ('texto', 'Texto'), ('seleccion', 'Selección')], default='booleano', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_core.plantillachecklist')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='platform_core.checklistregistro')),
                ('item_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.plantillachecklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('tipo_entidad', models.CharField(choices=[('tracto', 'Tractocamión'), ('empleado', 'Empleado con vehículo asignado'), ('visitante', 'Visitante/Proveedor')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('tiene_evidencia', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='platform_core.conductor')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='platform_core.empleado')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('capturada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_capturadas', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='platform_core.checklistregistro')),
                ('registro_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='platform_core.registroacceso')),
            ],
        ),
        migrations.AddField(
            model_name='checklistregistro',
            name='registro_acceso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='platform_core.registroacceso'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('nocturno', 'Nocturno')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora_apertura', models.DateTimeField()),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('abierto', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='platform_core.turno'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('guardia', 'Guardia')], max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_active_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='platform_core.vehiculo'),
        ),
        migrations.CreateModel(
            name='AsignacionVehiculoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_asignados', to='platform_core.empleado')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_empleado', to='platform_core.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='platform_core.visitanteregistro'),
        ),
    ]
