# Generated by Django 6.0.3 on 2026-04-30 20:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTractoItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('seccion', models.CharField(choices=[('accesorios', 'Accesorios y herramientas'), ('apariencia', 'Apariencia general'), ('ventanas', 'Ventanas'), ('espejos', 'Espejos'), ('luces', 'Luces'), ('aceite', 'Aceite'), ('enfriamiento', 'Enfriamiento'), ('fugas', 'Fugas'), ('frenos', 'Frenos'), ('loderas', 'Loderas'), ('combustible', 'Sistema de combustible'), ('otros', 'Otros')], max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='checklist_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='checklist_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/accesos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('modulo', models.CharField(choices=[('turnos', 'Turnos'), ('accesos', 'Registro de acceso'), ('checklist_tracto', 'Checklist tracto'), ('perfil', 'Perfil'), ('catalogos', 'Catálogos'), ('sistema', 'Sistema')], max_length=30)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('cerrar', 'Cerrar'), ('consultar', 'Consultar'), ('subir_evidencia', 'Subir evidencia'), ('login', 'Inicio de sesión'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('entidad_tipo', models.CharField(blank=True, max_length=50)),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='platform_core.turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estatus_general', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('condicionado', 'Condicionado')], max_length=20)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('firma_operador_data', models.TextField(blank=True, null=True)),
                ('firma_vigilante_data', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_tracto', to='platform_core.conductor')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_tracto', to=settings.AUTH_USER_MODEL)),
                ('registro_acceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_tracto', to='platform_core.registroacceso')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_tracto', to='platform_core.turno')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_tracto', to='platform_core.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTractoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='checklists/tracto/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('uuid_evidencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='platform_core.checklisttracto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTractoLlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('delantera_izquierda', 'Delantera izquierda'), ('delantera_derecha', 'Delantera derecha'), ('trasera_exterior_izquierda', 'Trasera exterior izquierda'), ('trasera_interior_izquierda', 'Trasera interior izquierda'), ('trasera_interior_derecha', 'Trasera interior derecha'), ('trasera_exterior_derecha', 'Trasera exterior derecha'), ('remolque_1_izquierda', 'Remolque 1 izquierda'), ('remolque_1_derecha', 'Remolque 1 derecha'), ('remolque_2_izquierda', 'Remolque 2 izquierda'), ('remolque_2_derecha', 'Remolque 2 derecha')], max_length=40)),
                ('estado', models.CharField(choices=[('ok', 'Correcta'), ('regular', 'Regular'), ('mal', 'Con daño'), ('na', 'No aplica')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llantas', to='platform_core.checklisttracto')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('checklist', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistTractoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('ok', 'Correcto'), ('mal', 'Con daño / falla'), ('na', 'No aplica')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='platform_core.checklisttracto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='platform_core.checklisttractoitemcatalogo')),
            ],
            options={
                'ordering': ['item__seccion', 'item__orden', 'id'],
                'unique_together': {('checklist', 'item')},
            },
        ),
    ]
