# Generated by Django 6.0.3 on 2026-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_checklisttractoitemcatalogo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionvehiculoempleado',
            options={'ordering': ['-fecha_asignacion']},
        ),
        migrations.AlterModelOptions(
            name='checklistregistro',
            options={'ordering': ['-fecha_hora', '-id']},
        ),
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['nombre_completo']},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre_completo']},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-fecha_hora', '-id']},
        ),
        migrations.AlterModelOptions(
            name='plantillachecklist',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='plantillachecklistitem',
            options={'ordering': ['plantilla', 'orden']},
        ),
        migrations.AlterModelOptions(
            name='registroacceso',
            options={'ordering': ['-fecha_hora', '-id']},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha', '-hora_apertura']},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa']},
        ),
        migrations.AlterModelOptions(
            name='visitanteregistro',
            options={'ordering': ['nombre_completo']},
        ),
        migrations.AlterField(
            model_name='checklistregistro',
            name='resultado_general',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('condicionado', 'Condicionado')], default='pendiente', max_length=50),
        ),
    ]
