# Generated by Django 6.0.3 on 2026-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_alter_asignacionvehiculoempleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='firma_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones_cierre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
