# Generated by Django 6.0.3 on 2026-05-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_add_turno_cierre_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_asignado', to='platform_core.vehiculo'),
        ),
    ]
