# Generated by Django 6.0.3 on 2026-05-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0005_add_vehiculo_to_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='conductor_pendiente_salida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='entrada_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_asociadas', to='platform_core.registroacceso'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_conductor', to='platform_core.conductor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='en_instalacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultimo_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_ultimo_empleado', to='platform_core.empleado'),
        ),
    ]
