# Generated by Django 6.0.3 on 2026-05-13 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_add_control_instalacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='par_id',
            field=models.UUIDField(blank=True, help_text='UUID que vincula entrada con salida', null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='tipo_entidad',
            field=models.CharField(choices=[('tracto', 'Tractocamión'), ('empleado', 'Empleado con vehículo asignado'), ('empleado_propio', 'Empleado con vehículo propio'), ('visitante', 'Visitante/Proveedor'), ('conductor', 'Conductor (vehículo propio)')], max_length=20),
        ),
        migrations.CreateModel(
            name='AsignacionEmpleadoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='platform_core.empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_empleado', to='platform_core.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación Empleado-Vehículo',
                'verbose_name_plural': 'Asignaciones Empleado-Vehículo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionConductorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='platform_core.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_conductor', to='platform_core.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación Conductor-Vehículo',
                'verbose_name_plural': 'Asignaciones Conductor-Vehículo',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('conductor', 'activa'), name='unique_conductor_asignacion_activa')],
            },
        ),
        migrations.CreateModel(
            name='BitacoraCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_affectada', models.CharField(max_length=100)),
                ('registro_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('ASIGNAR', 'Asignación'), ('DESASIGNAR', 'Desasignación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('REGISTRO_ENTRADA', 'Registro de entrada'), ('REGISTRO_SALIDA', 'Registro de salida')], max_length=20)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Cambio',
                'verbose_name_plural': 'Bitácoras de Cambios',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['tabla_affectada', 'registro_id'], name='platform_co_tabla_a_a7104f_idx'), models.Index(fields=['fecha_hora'], name='platform_co_fecha_h_acc685_idx'), models.Index(fields=['usuario'], name='platform_co_usuario_c5389a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialUsoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('tipo_entidad', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dentro_instalacion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_uso', to='platform_core.conductor')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_uso', to='platform_core.empleado')),
                ('registro_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_uso', to='platform_core.registroacceso')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_uso', to='platform_core.turno')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_uso', to='platform_core.vehiculo')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_uso', to='platform_core.visitanteregistro')),
            ],
            options={
                'verbose_name': 'Historial de Uso de Vehículo',
                'verbose_name_plural': 'Historiales de Uso de Vehículos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['vehiculo', 'dentro_instalacion'], name='platform_co_vehicul_cbf1ec_idx'), models.Index(fields=['fecha_hora'], name='platform_co_fecha_h_527e6a_idx')],
            },
        ),
    ]
