# Generated by Django 6.0.3 on 2026-05-14 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0007_registroacceso_par_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='modulo',
            field=models.CharField(choices=[('turnos', 'Turnos'), ('accesos', 'Registro de acceso'), ('checklist_tracto', 'Checklist tracto'), ('perfil', 'Perfil'), ('catalogos', 'Catálogos'), ('sistema', 'Sistema'), ('usuarios', 'Usuarios')], max_length=30),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('turno_abierto', 'Turno abierto'), ('turno_cerrado', 'Turno cerrado'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('info', 'Información')], default='info', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
