# Generated by Django 6.0.3 on 2026-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0008_alter_auditlog_modulo_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('cerrar', 'Cerrar'), ('consultar', 'Consultar'), ('subir_evidencia', 'Subir evidencia'), ('login', 'Inicio de sesión'), ('eliminar', 'Eliminar'), ('asignar', 'Asignar'), ('desasignar', 'Desasignar'), ('otro', 'Otro')], max_length=30),
        ),
    ]
