# Generated by Django 6.0.3 on 2026-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0009_alter_auditlog_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.CharField(blank=True, choices=[('LRA', 'LRA'), ('PRO', 'PRO'), ('CON', 'CON')], max_length=20),
        ),
    ]
