# Generated by Django 6.0.3 on 2026-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0011_add_tipo_respuesta_to_checklistcatalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttracto',
            name='firma_supervisor_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklisttracto',
            name='nombre_operador',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='checklisttracto',
            name='nombre_supervisor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='checklisttracto',
            name='nombre_vigilante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='checklisttractoevidencia',
            name='seccion',
            field=models.CharField(choices=[('accesorios', 'Accesorios'), ('luces', 'Luces'), ('motor', 'Motor'), ('frenos', 'Frenos'), ('llantas', 'Llantas'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='checklisttractoitemcatalogo',
            name='seccion',
            field=models.CharField(choices=[('combustible', 'Combustible'), ('habitaculo', 'Habitáculo'), ('luz_y_visibilidad', 'Luz y Visibilidad'), ('motor_y_chasis', 'Motor y Chasis'), ('seguridad', 'Seguridad'), ('accesorios', 'Accesorios y herramientas'), ('apariencia', 'Apariencia general'), ('ventanas', 'Ventanas'), ('espejos', 'Espejos'), ('luces', 'Luces'), ('aceite', 'Aceite'), ('enfriamiento', 'Enfriamiento'), ('fugas', 'Fugas'), ('frenos', 'Frenos'), ('loderas', 'Loderas'), ('otros', 'Otros')], max_length=30),
        ),
    ]
