# Generated by Django 6.0.3 on 2026-03-22 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('nombre_conductor', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_vehiculares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Vehicular',
                'verbose_name_plural': 'Registros Vehiculares',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
